<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CASH' => '',
    'Download' => 'Tải xuống',
    'ID' => '',
    'Off Post' => '',
    'Post1s' => '',
    'Title' => 'Tiêu đề',
    'Tạm ứng' => '',
    ' No such file or directory' => 'Không có tập tin hoặc thư mục',
    'Accom Doc' => 'Chứng từ',
    'Accom Doc Pay' => 'Chứng từ',
    'Add New Post' => 'Thêm bài viết',
    'Advance Payment' => 'Tạm ứng',
    'All Posts' => 'Tất cả bài viết',
    'Amount' => 'Số tiền tạm ứng',
    'Are you sure you want to delete this item ?' => 'Bạn chắc chắn muốn xóa mục này',
    'Are you sure you want to delete this item?' => 'Bạn chắc chắn muốn xóa mục này ?',
    'Attach File' => 'Đính kèm tập tin',
    'Content' => 'Nội dung',
    'Content Pay' => 'Nội dung',
    'Cost' => 'Chi phí',
    'Create' => 'Tạo mới',
    'Create At' => 'Ngày tạo',
    'Create By' => 'Người tạo',
    'Create Post' => 'Tạo mới',
    'Create Post1' => 'Tạo mới',
    'Date Issued' => 'Ngày ban hành',
    'Deadline' => 'Thời hạn hoàn ứng',
    'Delete' => 'Xóa',
    'Department' => 'Bộ phận',
    'Department Pay' => 'Bộ phận',
    'Download file' => 'Tải tập tin',
    'Draft Cash' => 'Bản nháp',
    'Draft Post' => 'Bản Nháp',
    'Edit' => 'Chỉnh sửa',
    'Expiry Day' => 'Ngày hết hạn',
    'From Date issued' => 'Từ ngày ban hành',
    'Link download' => 'Đường dẫn',
    'List Post' => 'Danh sách bài viết',
    'Listing Advance' => 'Danh sách tạm ứng',
    'Listing Advances' => 'Danh sách tạm ứng',
    'Listing Payments' => 'Danh sách thanh toán',
    'Note' => 'Ghi chú',
    'Note Pay' => 'Ghi chú',
    'Offer By' => 'Người đề nghị',
    'Offer By Pay' => 'Người đề nghị',
    'Offer by' => 'Người đề nghị',
    'Pay' => 'Đã thanh toán',
    'Payment' => 'Thanh toán',
    'Confirm' => 'Xác nhận',
    'Payment Now' => 'Thanh toán ngay',
    'Payment Pay' => 'Phương thức thanh toán',
    'Payment now' => 'Thanh toán ngay',
    'People Signing' => 'Người ban hành',
    'Post Content' => 'Nội dung',
    'Post Excerpt' => 'Nội dung tóm tắt',
    'Post Status' => 'Trang thái',
    'Post Title' => 'Tiêu đề',
    'Post title' => 'Tiêu đề',
    'Print' => 'In',
    'Recycle bin' => 'Thùng rác',
    'Remove' => 'Xóa',
    'Reset' => 'Làm mới',
    'Restore' => 'Phục hồi',
    'Search' => 'Tìm kiếm',
    'Select Option' => 'Tùy chọn',
    'Select..' => 'Chọn',
    'Start Day' => 'Ngày bắt đầu',
    'Status' => 'Hình thức',
    'To date issued' => 'Đến ngày ban hành',
    'Update' => 'Cập nhật',
    'Update At' => 'Ngày cập nhật',
    'Update By' => 'Người cập nhật',
    'Update {modelClass}: ' => 'Cập nhật {modelClass}',
    'View detail ' => 'Xem chi tiết',
    'deleted' => 'Đã xóa',
    'draft' => 'Nháp',
    'off' => 'Tắt',
    'on' => 'Bật',
    'payment now' => 'Thanh toán ngay',
    'ready cash' => 'Tiền mặt',
    'restore' => 'Phục hồi',
    'transfer' => 'Chuyển khoản',
    '{expiry day} must be greater than "{start day}".' => 'Ngày hết hạn phải lớn hơn Ngày bắt đầu.',
    '{start day} must be greater than "{date issued}".' => 'Ngày bắt đầu phải lớn hơn ngày ban hành',
];
