<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ACCOMMODATIONS' => '',
    'Age' => '',
    'Arrival time' => '',
    'Contact number' => '',
    'Date' => '',
    'Departure time' => '',
    'Destination' => '',
    'EMERGENCY CONTACTS' => '',
    'FLIGHTS' => '',
    'Full name' => '',
    'Guide & Driver' => '',
    'Hotel/Resort & Website' => '',
    'Itinerary' => '',
    'LIST OF TRAVELLERS' => '',
    'Meals' => '',
    'Move up/down' => '',
    'No. of nights' => '',
    'Number' => '',
    'PROGRAM IN BRIEF' => '',
    'Person in charge' => '',
    'Remove' => '',
    'Room type' => '',
    'Rooming' => '',
    'Route' => '',
    'Service time' => '',
    'THE TOUR' => '',
    'TOUR GUIDE DETAILS' => '',
    'TRAINS' => '',
    'Title' => '',
    'Tour guide' => '',
    'Train route' => '',
    'Website' => '',
];
