<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to cancel this tour' => '',
    'CHÚ Ý' => '',
    'Chỉ người quản lý và người điều hành tour mới có thể huỷ tour. Các điều sau đây sẽ xảy ra trên hệ thống khi bạn quyết định huỷ tour này' => '',
    'Các booking (đã được confirm) sẽ được chuyển thành BỊ HUỶ (canceled)' => '',
    'Go back' => '',
    'Tour được đánh dấu trạng thái BỊ HUỶ (canceled)' => '',
    'Yes, cancel this tour' => '',
];
