<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '' => '',
    'Add service' => '',
    'Admin' => '',
    'Admin/Resv' => '',
    'Ai thanh toán' => '',
    'Booking status' => '',
    'Cancel' => '',
    'Cho kế toán' => '',
    'Day in tour' => '',
    'Giá tiền' => '',
    'Giám đốc duyệt lần cuối' => '',
    'GĐ' => '',
    'Ha Noi' => '',
    'Hotel, sightseeing' => '',
    'KTT' => '',
    'Kế toán trưởng xác nhận' => '',
    'Kế toán đánh dấu đã thanh toán' => '',
    'Name of service' => '',
    'Ngày này không nằm trong chương trình tour chính thức' => '',
    'Nha Trang' => '',
    'Nhà cung cấp' => '',
    'Note (optional)' => '',
    'Number' => '',
    'Nội dung' => '',
    'Payment due' => '',
    'Prebooking needed' => '',
    'Provider/Venue' => '',
    'Quantity' => '',
    'Save as copy' => '',
    'Save changes' => '',
    'Siem Reap' => '',
    'Số' => '',
    'Sửa dịch vụ tour' => '',
    'TRẢ' => '',
    'Thành VND' => '',
    'Thêm / Xem các ghi chú' => '',
    'Time' => '',
    'Tàu, xe, dịch vụ gốc' => '',
    'Tỉ giá' => '',
    'Unit' => '',
    'Unit price' => '',
    'Venue/location' => '',
    'Vientiane' => '',
    'Vé tàu, vé máy bay, package' => '',
    'Who pays' => '',
    'note' => '',
    'Điều hành đánh dấu đã đặt xong' => '',
    'Đvị' => '',
    'Đại lý' => '',
    'Đối tác / Cung cấp' => '',
];
