<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Ai trả' => '',
    'Ai đặt' => '',
    'Bán hàng' => '',
    'CSKH' => '',
    'Chi phí' => '',
    'Chi phí tour chi tiết theo ngày' => '',
    'Chương trình tour' => '',
    'Code' => '',
    'Giá' => '',
    'Giá tour' => '',
    'Guide m Bắc' => '',
    'Khởi hành' => '',
    'Kinh doanh' => '',
    'Kiểm soát' => '',
    'Kế toán' => '',
    'Ngày' => '',
    'Ngày in' => '',
    'Ngày tính tỉ giá' => '',
    'Nhà c/cấp' => '',
    'Notes' => '',
    'Nội dung' => '',
    'Nội dung hoạt động (Bữa ăn)' => '',
    'Số' => '',
    'Số khách' => '',
    'Số ngày' => '',
    'TT' => '',
    'Thành VND' => '',
    'Tiền' => '',
    'Trưởng phòng ĐH' => '',
    'Tên đoàn' => '',
    'Tỉ giá' => '',
    'Xe m Bắc' => '',
    'ngày' => '',
    'tỉ giá mặc định' => '',
    'Điều hành' => '',
    'Đvị' => '',
    'Đã được duyệt ngày' => '',
];
