<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CHÚ Ý' => '',
    'Nếu có nhiều tên guide / lái xe thì điền các tên cách nhau bằng dấu phẩy' => '',
    'Nếu không biết tên guide / lái xe mà vẫn muốn in câu hỏi phần đó ra form thì phải điền tên là' => '',
    'Nếu để trống phần tên guide / lái xe thì form sẽ không in ra câu hỏi cho phần đó' => '',
    'Select a logo option' => '',
    'TOUR ITINERARY' => '',
    'This tour is from ' => '',
];
